#ifndef CASIMIR_CONFIGURATION_H_
#define CASIMIR_CONFIGURATION_H_

#define CASIMIR_VERSION_MAJOR 0
#define CASIMIR_VERSION_MINOR 0
#define CASIMIR_VERSION_PATCH 0
#define CASIMIR_VERSION       0.0.0
#define CASIMIR_HOMEPAGE      
#define CASIMIR_DESCRIPTION   

/* #undef CASIMIR_BUILD_SHARED */

#ifdef CASIMIR_BUILD_SHARED
    #define CASIMIR_EXPORT __declspec( dllexport )
#else
    #define CASIMIR_EXPORT 
#endif

#endif
