name: Ubuntu

on: [push]

jobs:
  test:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout submodule
        run: git submodule update --init --recursive
      - name: Configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCASIMIR_TESTS=ON ..
      - name: Build
        run: cd build && cmake --build . --config Release
      - name: Run test
        run: cd build && ctest -C Release --verbose